#!/bin/bash

set -eux

test $USER = "root" || { echo 'This script must be run as root'; exit 1; }

cd $(dirname $0)

./Run gindex

lshw > results/$(hostname)-$(date -I)-lshw.txt

uname -a > results/$(hostname)-$(date -I)-uname-a.txt

echo 'All done.'
